// APPLICATIONS CONSTANTS

const APPROVE_APPLICATION         = 'APPROVE_APPLICATION';
const APPROVE_APPLICATION_FAILED  = 'APPROVE_APPLICATION_FAILED';
const BOOKMARK_APPLICATION        = 'BOOKMARK_APPLICATION';
const DECLINE_APPLICATION         = 'DECLINE_APPLICATION';
const DECLINE_APPLICATION_FAILED  = 'DECLINE_APPLICATION_FAILED';
const GET_APPLICATION             = 'GET_APPLICATION';
const GET_APPLICATIONS            = 'GET_APPLICATIONS';
const POST_APPROVE_APPLICATION    = 'POST_APPROVE_APPLICATION';
const POST_DECLINE_APPLICATION    = 'POST_DECLINE_APPLICATION';
const SHOW_APPLICATION            = 'SHOW_APPLICATION';
const SHOW_APPLICATION_FAILED     = 'SHOW_APPLICATION_FAILED';
const SHOW_APPLICATIONS           = 'SHOW_APPLICATIONS';
const SHOW_APPLICATIONS_FAILED    = 'SHOW_APPLICATIONS_FAILED';

export {
  APPROVE_APPLICATION,
  APPROVE_APPLICATION_FAILED,
  BOOKMARK_APPLICATION,
  DECLINE_APPLICATION,
  DECLINE_APPLICATION_FAILED,
  GET_APPLICATION,
  GET_APPLICATIONS,
  POST_APPROVE_APPLICATION,
  POST_DECLINE_APPLICATION,
  SHOW_APPLICATION,
  SHOW_APPLICATION_FAILED,
  SHOW_APPLICATIONS,
  SHOW_APPLICATIONS_FAILED,
};